apiVersion: v1
kind: Service
metadata:
  name: nginx-minikube-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - name: webtest
      port: 80
      targetPort: 80
    - name: global-gate
      port: 3306
      targetPort: 3306
    - name: olap-gate
      port: 3316
      targetPort: 3316
    - name: oltp-gate
      port: 3326
      targetPort: 3326
    - name: vtctld-dashboard
      port: 15000
      targetPort: 15000
    - name: vtgate-dashboard
      port: 15001
      targetPort: 15001
    - name: vtctld-grpc
      port: 15999
      targetPort: 15999
    - name: vtgate-grpc
      port: 16000
      targetPort: 16000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      # nodePort: 30007